language: java

jdk:
  - oraclejdk7
  - openjdk7
install:
  - pwd
  - cd ..
  - git clone https://github.com/peshkira/fits-blackbox-testing.git
  - git clone https://github.com/openplanets/fits.git
  - cd fits-output-testing-mocks
